
# The containers that compose the project
services:
  db:
    image: postgres:latest
    restart: always
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests