services:
  db:
    image: postgres:latest
    restart: always
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: jimhats