spring.application.name=jim-hats-web-api
spring.datasource.url=jdbc:postgresql://localhost:5432/jim_hats_db
spring.datasource.username=jim-hats-web-api
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto=update
