spring.application.name=jim-hats-web-api
spring.datasource.url=jdbc:mysql://localhost:3306/jim_hats_db
spring.datasource.username=jim-hats-web-api
spring.datasource.password=senhasegura
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto=update
